AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/textris-delivery-ovh.rb'

Layout/LineLength:
  Exclude:
    - 'textris-delivery-ovh.gemspec'
